export {default as Home} from './Home/Home'
export {default as Shooting} from './Shooting/Shooting'
export {default as Locations} from './Locations/Locations'
export {default as LocationOzieri} from './LocationOzieri/LocationOzieri'
export {default as Partners} from './Partners/Partners'
export {default as Progetto} from './Progetto/Progetto'
export {default as SocialWall} from './SocialWall/SocialWall'